function L = limites_tramos()
% Devuelve estructura con los límites EUROCONTROL por tipo de tramo

L = struct( ...
    'uniforme', struct('long', 60, 'trans', 60, 'vel', 0.6, 'rumbo', 0.7), ...
    'acelerado', struct('long', 180, 'trans', 60, 'vel', 17, 'rumbo', 1.5), ...
    'giro', struct('long', 100, 'trans', 100, 'vel', 4, 'rumbo', 6) ...
);

end